apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomquotes
  labels:
    app: randomquotes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: randomquotes
  template:
    metadata:
      labels:
        app: randomquotes
    spec:
      containers:
        - name: randomquotes
          image: ghcr.io/vlussenburg/octopus-iac-lab:1.1.15
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
