apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: randomquotes
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: randomquotes
                port:
                  number: 80
